import { test, expect } from '@playwright/test';
import { operationFixture, post } from './operation-fixture';

test('painel filtra, alterna lista/quadro e abre a OS correta no celular e desktop', async ({ page }, testInfo) => {
  const order = await operationFixture(page.request);
  const vehicle = await post(page.request, '/api/veiculos', { clienteId: order.clienteId, placa: 'ABC1234', marca: 'Honda', modelo: 'Civic', ano: 2020, cor: 'Preto' });
  const second = await post(page.request, '/api/ordens-servico', { clienteId: order.clienteId, veiculoId: vehicle.id,
    relatoInicial: 'Revisar sistema de freios.', entradaEm: new Date().toISOString(), kmEntrada: 30000, previsaoEm: null });
  await post(page.request, `/api/ordens-servico/${second.id}/status`, { status: 'AGUARDANDO_PECAS', expectedVersion: 0 });
  await page.goto('/painel?view=lista');
  await expect(page.getByRole('heading', { name: 'O ritmo da oficina.' })).toBeVisible();
  await expect(page.locator('app-dashboard-card')).toHaveCount(2);
  await expect(page.getByRole('button', { name: '1 Atrasadas', exact: true })).toBeVisible();
  await page.getByRole('button', { name: '1 Atrasadas', exact: true }).click();
  await expect(page.locator('app-dashboard-card')).toHaveCount(1);
  await expect(page.locator('app-dashboard-card')).toContainText('BRA-1E23');
  await page.getByRole('button', { name: 'Limpar', exact: true }).click();
  await expect(page.locator('app-dashboard-card')).toHaveCount(2);
  await page.getByLabel('Buscar por placa, cliente ou OS').fill('ABC-1234');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.locator('app-dashboard-card')).toHaveCount(1);
  await expect(page.locator('app-dashboard-card')).toContainText('Aguardando peças');
  await page.getByRole('button', { name: 'Quadro Kanban', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Aguardando peças', exact: true }).locator('app-dashboard-card')).toHaveCount(1);
  await page.reload();
  await expect(page.getByLabel('Buscar por placa, cliente ou OS')).toHaveValue('ABC-1234');
  await expect(page.locator('app-dashboard-card')).toHaveCount(1);
  await page.getByRole('link', { name: `Abrir OS-${second.numero}`, exact: true }).click();
  await expect(page).toHaveURL(new RegExp(`id=${second.id}`));
  await expect(page.locator('.editor .plate')).toHaveText('ABC-1234');
  await page.goto(`/ordens-servico?id=${order.id}`);
  await expect(page.locator('.editor .plate')).toHaveText('BRA-1E23');
  await page.goto('/painel?view=lista');
  await expect(page.locator('app-dashboard-card')).toHaveCount(2);
  if (testInfo.project.name === 'mobile') await page.setViewportSize({ width: 320, height: 740 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: testInfo.outputPath('painel.png'), fullPage: true });
  await page.getByRole('button', { name: 'Quadro Kanban', exact: true }).click();
  await expect(page.getByRole('region', { name: 'Quadro Kanban', exact: true })).toBeVisible();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= window.innerWidth)).toBeTruthy();
  await page.screenshot({ path: testInfo.outputPath('painel-quadro.png'), fullPage: true });
  await page.getByLabel('Buscar por placa, cliente ou OS').fill('inexistente');
  await page.getByRole('button', { name: 'Aplicar filtros' }).click();
  await expect(page.getByRole('heading', { name: 'Nenhum atendimento nesta busca.' })).toBeVisible();
  await page.route('**/api/painel?**', route => route.fulfill({ status: 500, contentType: 'application/json', body: '{}' }));
  await page.getByRole('button', { name: 'Atualizar', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Não foi possível carregar');
  await page.unroute('**/api/painel?**');
  await page.getByRole('button', { name: 'Tentar novamente' }).click();
  await expect(page.getByRole('heading', { name: 'Nenhum atendimento nesta busca.' })).toBeVisible();
});
