import { test, expect } from '@playwright/test';

test('configuração, horários, logo e perfil público automático', async ({ page, browser }, info) => {
  const email = `shop-${Date.now()}-${info.project.name}@example.test`;
  await page.goto('/cadastro');
  await page.getByLabel('Seu nome', { exact: true }).fill('Dono Teste');
  await page.getByLabel('Nome da oficina').fill('Oficina inicial');
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill('Oficina-segura-123');
  await page.getByLabel('Confirmar senha').fill('Oficina-segura-123');
  await page.getByRole('button', { name: 'Criar minha conta' }).click();
  await expect(page.getByRole('status')).toBeVisible();
  await page.getByRole('link', { name: /Ir para o login/ }).click();
  await page.getByLabel('E-mail', { exact: true }).fill(email);
  await page.getByLabel('Senha', { exact: true }).fill('Oficina-segura-123');
  await page.getByRole('button', { name: 'Entrar na oficina' }).click();
  await page.getByRole('link', { name: 'Perfil', exact: true }).click();
  await expect(page.getByLabel('Nome da oficina *', { exact: true })).toHaveValue('Oficina inicial');
  await expect(page.getByLabel('Oficina sem logo')).toBeVisible();
  await page.getByLabel('Nome da oficina *', { exact: true }).fill('Oficina Horizonte');
  await page.getByLabel('Telefone de contato').fill('(61) 3333-4444');
  await page.getByLabel('E-mail de contato').fill('contato@example.test');
  await page.getByLabel('Endereço', { exact: true }).fill('Rua das Oficinas, 123');
  await page.getByLabel('Abertura').first().fill('08:00');
  await page.getByLabel('Fechamento').first().fill('18:00');
  await page.getByRole('button', { name: 'Salvar informações' }).click();
  await expect(page.getByRole('status')).toContainText('salva');
  await page.reload();
  await expect(page.getByLabel('Telefone de contato')).toHaveValue('(61) 3333-4444');
  await page.route('**/api/oficina', async route => {
    if (route.request().method() === 'PATCH') await route.abort();
    else await route.continue();
  });
  await page.getByLabel('Endereço', { exact: true }).fill('Rua das Oficinas, 456');
  await page.getByRole('button', { name: 'Salvar informações' }).click();
  await expect(page.getByRole('alert')).toBeVisible();
  await expect(page.getByLabel('Endereço', { exact: true })).toHaveValue('Rua das Oficinas, 456');
  await expect(page.getByRole('status')).toHaveCount(0);
  await page.unroute('**/api/oficina');
  await page.getByLabel('Endereço', { exact: true }).fill('Rua das Oficinas, 123');
  await page.getByLabel('Selecionar logo').setInputFiles({ name: 'fake.png', mimeType: 'image/png', buffer: Buffer.from('invalid png') });
  await expect(page.getByRole('alert')).toContainText('válida');
  // A real screenshot provides a PNG fixture without trusting the file extension.
  const png = await page.screenshot();
  await page.getByLabel('Selecionar logo').setInputFiles({ name: 'logo.png', mimeType: 'image/png', buffer: png });
  await expect(page.getByRole('status')).toContainText('salva');
  await expect(page.getByRole('img', { name: 'Logo de Oficina Horizonte' })).toBeVisible();
  const publicPath = await page.getByRole('link', { name: 'Abrir perfil publicado' }).getAttribute('href');
  const publicContext = await browser.newContext();
  const publicPage = await publicContext.newPage();
  await publicPage.goto(publicPath!);
  await expect(publicPage.getByRole('heading', { name: 'Oficina Horizonte' })).toBeVisible();
  await expect(publicPage.getByText('Rua das Oficinas, 123')).toBeVisible();
  expect(await publicPage.locator('body').innerText()).not.toContain(email);
  await page.screenshot({ path: `test-results/shop-${info.project.name}.png`, fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.setViewportSize({ width: 320, height: 760 });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBeTruthy();
  await page.getByRole('button', { name: 'Remover logo' }).click();
  await expect(page.getByLabel('Oficina sem logo')).toBeVisible();
  await publicPage.reload();
  await expect(publicPage.getByRole('heading', { name: 'Oficina Horizonte' })).toBeVisible();
  await publicContext.close();
});
